name: Push github directory to another azure devops repository
on:
  push:
    branches:
      - '*' # Applies to all branches in GitHub
  workflow_dispatch: # Manual trigger from GitHub UI
  
jobs:
  sync-to-azure:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # CRITICAL: Fetches all history for all branches so git sync works properly

    - name: Run Sync Script
      env:
        AZUREPAT: ${{ secrets.AZUREPAT }}
        AZUSERNAME: ${{ secrets.AZUSERNAME }}
        AZUSER_EMAIL: ${{ secrets.AZUSER_EMAIL }}
        AZORG: ${{ secrets.AZORG }}
      run: |
         chmod +x ./script/commit.sh
         ./script/commit.sh
      shell: bash
